apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-plugins
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi