name: Infrastructure Deployment
on: 
  push:
    branches:
      - main
    paths:
      - 'env/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Deploy Bicep files
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          template: ./env/main.bicep
          parameters: location={{ secrets.LOCATION }} localAddressPrefixes=${{ secrets.LOCAL_ADDRESS_PREFIX }} localGatewayIpAddress=${{ secrets.LOCAL_GATEWAY_IP }} vpnPreSharedKey=${{ secrets.VPN_KEY }}
          failOnStdErr: false
    