name: Infrastructure Deployment
on: 
  push:
    branches:
      - main
    paths:
      - 'env/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     
      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Deploy Bicep files
      - name: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: ${{ secrets.LOCATION }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          template: ./env/main.bicep
          parameters: location=${{ secrets.LOCATION }} localAddressPrefixes=${{ secrets.LOCAL_ADDRESS_PREFIX }} localGatewayIpAddress=${{ secrets.LOCAL_GATEWAY_IP }} vpnPreSharedKey=${{ secrets.VPN_KEY }} adminUsername=${{ secrets.ADMIN_USERNAME }} adminPassword=${{ secrets.ADMIN_PASSWORD }} notificationSenderEmail=${{ secrets.NOTIFICATION_EMAIL }} publisherEmail=${{ secrets.NOTIFICATION_EMAIL }} publisherName=${{ secrets.PUBLISHER_NAME }} 
          failOnStdErr: false
    