name: Infrastructure Deployment
on: 
  push:
    branches:
      - main
    paths:
      - 'env/**'
jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
     
      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Deploy Bicep files
      - name: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RG }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          template: ./env/main.bicep
          parameters: userId=${{ secrets.ADMINUSERID }} aksClusterSshPublicKey='' actionGroupEmailAddress=${{ secrets.ACTION_GROUP_EMAIL }} deploymentScriptUri='https://raw.githubusercontent.com/jgardner04/home-lab/main/env/deploy.sh' namespace='demo' serviceAccountName=${{ secrets.SERVICE_ACCOUNT_NAME }} vmAdminPasswordOrKey=${{ secrets.VM_PASSWORD }} vmAdminUsername=${{ secrets.VM_USER }} applicationGatewayPrivateIpAddress={{ secrets.APP_GATEWAY_PRIVATE_IP}}
          failOnStdErr: false 

  # tailscale:
  #   runs-on: ubuntu-latest
  #   needs: infra
  #   steps:
  #   - uses: deliverybot/helm@master
  #     with:
  #       release: tailscale-subnet-router
  #       namespace: default
  #       chart: mvisonneau/tailscale-relay
  #       repo: https://charts.visonneau.fr
  #       repo-alias: mvisonneau
  #       values: |
  #         config.authKey: {{ secrets.TAILSCALE_AUTH_KEY}}
  #         config.variables.TAILSCALE_ADVERTISE_ROUTES: {{ secrets.TAILSCALE_ADVERTISE_ROUTES }}