# .github/workflows/monitoring.yml
name: Monitoring
on:
  workflow_run:
    workflows: ["Infrastructure Deployment"]
    types:
      - completed
    branches:
      - 'main'
  push:
    branches:
      - 'main'
    paths:
      - 'kubernetes/**'

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Setup kubectl
      - uses: azure/setup-kubectl@v3

      # Setup Helm
      - uses: azure/setup-helm@v3
      
      # Set AKS Context
      - uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RG }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
      
      # AKS supporting files
      - uses: azure/k8s-deploy@v4
        with:
          resource-group: ${{ secrets.AKS_RG }}
          name: ${{ secrets.AKS_CLUSTER_NAME }}
          action: deploy
          strategy: basic

          private-cluster: true
          manifests: |
            kubernetes/monitoring-namespace.yaml
            kubernetes/grafana-plugins-pvc.yaml
      
      # # Deploy Grafana
      # - name: Deploy Grafana
      #   run: |
      #     helm repo add grafana https://grafana.github.io/helm-charts
      #     helm repo update grafana
      #     helm upgrade --install grafana grafana/grafana --namespace=monitoring -f 'kubernetes/grafana/values.yaml