# .github/workflows/monitoring.yml
name: Monitoring
on:
  workflow_run:
    workflows:
      - "build-and-deploy"
    branches:
      - 'main'

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
