# .github/workflows/monitoring.yml
name: Monitoring
on:
  workflow_run:
    workflows:
      - "Infrastructure Deployment"
    types:
      - completed
    branches:
      - 'main'

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
